# Generated by Django 6.0.5 on 2026-05-24 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_client_id_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='service.employee', verbose_name='Сотрудник'),
        ),
    ]
